[package]
name = "statistics_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.14" 
reqwest = { version = "0.11", features = ["json", "blocking", "native-tls"] }
serde = "1.0.228"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
slint-build = "1.14"